## Задача №1

Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0]))

In [2]:
import numpy as np

In [15]:
x = int(input('Введите число элементов: '))
nums = np.arange(x)
nums

Введите число элементов: 12


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

## Задача №2

Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [185]:
x = int(input('Введите начальное значение диагональной матрицы: '))
y = int(input('Введите конечное значение диагональной матрицы: '))
diag_matrix = np.diag(np.arange(x,y))
sum_diag = 0
for i in diag_matrix:
    sum_diag += sum(i)
print(sum_diag)
print(diag_matrix)

Введите начальное значение диагональной матрицы: 1
Введите конечное значение диагональной матрицы: 4
6
[[1 0 0]
 [0 2 0]
 [0 0 3]]


## Задача №3

Решите систему уравнений:  


4x + 2y + z = 4  
x + 3y = 12  
5y + 4z = -3  

In [136]:
# правая часть уравнения
a = np.array([[4,2,1],[1,3,0],[0,5,4]])

# левая часть уравнения
b = np.array([4,12,-3])

from numpy import linalg

linalg.solve(a, b)


array([ 0.46666667,  3.84444444, -5.55555556])

## Задача №4

Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:

In [1]:
import numpy as np

In [2]:
from numpy import linalg

In [3]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
)

На сайт заходит очередной посетитель, о покупках которого известно следующее:

In [4]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [64]:
next_user_stats_Length = np.linalg.norm(next_user_stats)
for users in users_stats:
    users_Length= np.linalg.norm(users)
    cos_ = np.dot(users, next_user_stats ) / ( users_Length * next_user_stats_Length )
    print(cos_)


0.19999999999999996
0.8451542547285165
0.3999999999999999
0.7905694150420948
0.3999999999999999
0.0
0.0
0.9486832980505138
0.0
0.0
